
name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: 'x86'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller xlrd xlwt xlutils selenium colorama docopt

    - name: Lint with flake8
      run:
        flake8 . --count --exit-zero --max-complexity=16 --max-line-length=127 --statistics

    - name: Build with PyInstaller
      run: |
        pyinstaller -F yw.py
        copy dist/*.exe .
        7z a yw.zip *.exe files/

    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: false
        files:
          yw.zip
